# Generated by Django 5.1.3 on 2025-03-10 05:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_alter_contactus_created'),
    ]

    operations = [
        migrations.CreateModel(
            name='SiteSetting',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('about_us', models.TextField(blank=True, null=True, verbose_name='متن درباره ما')),
                ('contact_us', models.TextField(blank=True, null=True, verbose_name='متن تماس با ما')),
                ('copy_right', models.CharField(max_length=100, verbose_name='متن کپی رایت')),
                ('phone', models.CharField(blank=True, max_length=15, null=True, verbose_name='شماره تماس')),
                ('address', models.CharField(blank=True, max_length=100, null=True, verbose_name='آدرس')),
                ('email', models.EmailField(blank=True, max_length=50, null=True, verbose_name='ایمیل')),
                ('facebook_link', models.CharField(blank=True, default='https://facebook.com/username', max_length=200, null=True, verbose_name='لینک فیسبوک')),
                ('instagram_link', models.CharField(blank=True, default='https://instagram.com/username', max_length=200, null=True, verbose_name='لینک اینستاگرام')),
                ('telegram_link', models.CharField(blank=True, default='https://t.me/username', max_length=200, null=True, verbose_name='لینک تلگرام')),
            ],
            options={
                'verbose_name': 'تنظیمات سایت',
                'verbose_name_plural': 'تنظیمات سایت',
            },
        ),
    ]
